---
- name: Ensure service user and group
  user: { name: litellm, shell: /usr/sbin/nologin, create_home: false }

- name: Install runtime prerequisites
  apt:
    name: [python3.12-venv, python3-pip, python3-psycopg2]
    state: present
    update_cache: true

- name: Create application directory and cache with correct ownership
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: litellm
    group: litellm
  loop:
    - /opt/litellm
    - /opt/litellm/.cache

- name: Create venv as the litellm user
  become: true
  become_user: litellm
  command: python3.12 -m venv /opt/litellm
  args: { creates: /opt/litellm/bin/activate }

- name: Install/upgrade LiteLLM and its database dependencies
  command: /opt/litellm/bin/pip install --upgrade "litellm[proxy]" psycopg2-binary prisma PyYAML
  become: true
  become_user: litellm

- name: Create configuration directory
  file: { path: /etc/litellm, state: directory, mode: '0755' }

- name: Render env file and proxy config with correct permissions
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0640'
    owner: root
    group: litellm
  loop:
    - { src: 'litellm.env.j2', dest: '/etc/litellm/litellm.env' }
    - { src: 'litellm.config.yaml.j2', dest: '/etc/litellm/config.yaml' }
  notify: Restart litellm

- name: Configure systemd service
  ansible.builtin.include_tasks: systemd.yml