---
- name: Ensure service user and group
  ansible.builtin.user: { name: litellm, shell: /usr/sbin/nologin, create_home: false }

- name: Install runtime prerequisites
  ansible.builtin.apt:
    name: [python3.12-venv, python3-pip, python3-psycopg2]
    state: present
    update_cache: true

- name: Create application directory and cache with correct ownership
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: litellm
    group: litellm
  loop:
    - /opt/litellm
    - /opt/litellm/.cache

- name: Create venv as the litellm user
  become: true
  become_user: litellm
  ansible.builtin.command: python3.12 -m venv /opt/litellm
  args: { creates: /opt/litellm/bin/activate }

- name: Install/upgrade LiteLLM and its database dependencies
  become: true
  become_user: litellm
  ansible.builtin.command: /opt/litellm/bin/pip install --upgrade "litellm[proxy]" psycopg2-binary prisma PyYAML

- name: Deploy Prisma schema file
  ansible.builtin.template:
    src: schema.prisma.j2
    dest: /opt/litellm/schema.prisma
    owner: litellm
    group: litellm
    mode: '0644'

- name: Generate the Prisma client query engine
  become: true
  become_user: litellm
  ansible.builtin.command: /opt/litellm/bin/prisma generate
  args:
    chdir: /opt/litellm
  environment:
    PATH: "/opt/litellm/bin:{{ ansible_env.PATH }}"
    DATABASE_URL: "postgresql://{{ litellm_db_user }}:{{ litellm_db_password }}@{{ litellm_db_host }}:5432/{{ litellm_db_name }}"
    XDG_CACHE_HOME: "/opt/litellm/.cache"
  no_log: true

- name: Push the Prisma schema to the database
  become: true
  become_user: litellm
  ansible.builtin.command: /opt/litellm/bin/prisma db push
  args:
    chdir: /opt/litellm
  environment:
    PATH: "/opt/litellm/bin:{{ ansible_env.PATH }}"
    DATABASE_URL: "postgresql://{{ litellm_db_user }}:{{ litellm_db_password }}@{{ litellm_db_host }}:5432/{{ litellm_db_name }}"
    XDG_CACHE_HOME: "/opt/litellm/.cache"
  no_log: true

- name: Create configuration and log directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: litellm
    group: litellm
  loop:
    - /etc/litellm
    - /var/log/litellm

- name: Render env file and proxy config with correct permissions
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0640'
    owner: root
    group: litellm
  loop:
    - { src: 'litellm.env.j2', dest: '/etc/litellm/litellm.env' }
    - { src: 'litellm.config.yaml.j2', dest: '/etc/litellm/config.yaml' }
  notify: Restart litellm

- name: Configure systemd service
  ansible.builtin.include_tasks: systemd.yml
