# Global variables for the HX Infrastructure
domain_name: dev-test.hana-x.ai
dc_ip: 192.168.10.2

# --- Host Specific Variables ---

# Interface names gathered from fleet analysis
iface_map:
  hx-ca-server: enp0s31f6
  hx-dc-server: enp0s31f6
  hx-api-server: enp0s31f6
  hx-orchestrator-server: eno1
  hx-vectordb-server: eno1
  hx-llm01-server: enp131s0
  hx-llm02-server: eno1
  hx-postgres-server: eno1
  hx-webui-server: enp0s31f6
  hx-devops-server: eno1
  hx-dev-server: eno1
  hx-test-server: eno1
  hx-docs-server: enp2s0
  hx-metrics-server: eno1
  hx-fs-server: enp0s31f6

# Authoritative IP map
ip_map:
  hx-ca-server: "192.168.10.4/24"
  hx-dc-server: "192.168.10.2/24"
  hx-api-server: "192.168.10.5/24"
  hx-orchestrator-server: "192.168.10.8/24"
  hx-vectordb-server: "192.168.10.9/24"
  hx-llm01-server: "192.168.10.6/24"
  hx-llm02-server: "192.168.10.7/24"
  hx-postgres-server: "192.168.10.10/24"
  hx-webui-server: "192.168.10.11/24"
  hx-devops-server: "192.168.10.14/24"
  hx-dev-server: "192.168.10.12/24"
  hx-test-server: "192.168.10.13/24"
  hx-docs-server: "192.168.10.15/24"
  hx-metrics-server: "192.168.10.16/24"
  hx-fs-server: "192.168.10.17/24"

# DNS map with exception for the DC
dns_map:
  default: [192.168.10.2]
  hx-dc-server: [127.0.0.1]

# Services to verify from the DC using the hx_ca_trust role
san_check_targets:
  - name: "Qdrant (VectorDB)"
    address: "192.168.10.9"
    port: 6333
    servername: "hx-vectordb-server.dev-test.hana-x.ai"

# --- hx_pg_auth role toggles (non-secret) ---
hx_pg_hardening_reject_nossl: true
hx_pg_enforce_tls_floor: true

# --- hx_pg_auth role toggles (non-secret) ---
hx_pg_hardening_reject_nossl: true
hx_pg_enforce_tls_floor: true
