---
- name: Create systemd override directory for litellm
  ansible.builtin.file:
    path: /etc/systemd/system/litellm.service.d
    state: directory
    mode: '0755'

- name: Create a systemd override to inject the database URL
  ansible.builtin.copy:
    dest: /etc/systemd/system/litellm.service.d/override.conf
    mode: '0644'
    content: |
      [Service]
      Environment="DATABASE_URL=postgresql://{{ litellm_db_user }}:{{ litellm_db_password }}@{{ litellm_db_host }}:5432/{{ litellm_db_name }}"
  notify: Restart litellm
  no_log: true

- name: Install systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/litellm.service
    mode: '0644'
    content: |
      [Unit]
      Description=LiteLLM OpenAI-compatible proxy
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=litellm
      Group=litellm
      EnvironmentFile=/etc/litellm/litellm.env
      Environment="XDG_CACHE_HOME=/opt/litellm/.cache"
      Environment="PATH=/opt/litellm/bin:/usr/bin:/bin"
      WorkingDirectory=/opt/litellm
      ExecStart=/opt/litellm/bin/litellm --config /etc/litellm/config.yaml --host ${LITELLM_HOST} --port ${LITELLM_PORT}
      Restart=always
      RestartSec=5
      # Hardening
      NoNewPrivileges=true
      ProtectSystem=strict
      ProtectHome=true
      PrivateTmp=true
      ReadOnlyPaths=/etc/litellm
      ReadWritePaths=/var/log/litellm /opt/litellm/.cache
      [Install]
      WantedBy=multi-user.target
  notify: Restart litellm

- name: Enable service and flush handlers
  ansible.builtin.systemd:
    name: litellm
    enabled: yes
  notify: Restart litellm

- name: Flush handlers to apply restart now
  ansible.builtin.meta: flush_handlers
