---
# HX Infrastructure Development Environment Inventory
all:
  children:
    metrics:
      hosts:
        hx-metrics-server.dev-test.hana-x.ai:
          ansible_user: agent0
    
    api:
      hosts:
        hx-api-server.dev-test.hana-x.ai:
          ansible_user: agent0
    
    litellm:
      hosts:
        hx-api-server.dev-test.hana-x.ai:
          ansible_user: agent0
    
    postgres:
      hosts:
        hx-postgres-server.dev-test.hana-x.ai:
          ansible_user: agent0
    
    vectordb:
      hosts:
        hx-vectordb-server.dev-test.hana-x.ai:
          ansible_user: agent0
    
    webui:
      hosts:
        hx-webui-server.dev-test.hana-x.ai:
          ansible_user: agent0
