name: Ansible Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core ansible-lint yamllint
      - name: ansible-lint
        run: ansible-lint
      - name: yamllint
        run: yamllint .
